[platformio]
src_dir = .          ; compile DIM_M5Unified.ino directement

; ── M5Stack Core ─────────────────────────────────────────────────────────
[env:m5stack_core]
platform  = espressif32
board     = m5stack-core-esp32
framework = arduino
lib_deps  =
    m5stack/M5Unified @ ^0.2.14
    bblanchon/ArduinoJson @ ^7.0.0
build_flags = -DCORE_DEBUG_LEVEL=0
upload_speed = 921600

; ── M5Stack Core2 ────────────────────────────────────────────────────────
[env:m5stack_core2]
platform  = espressif32
board     = m5stack-core2
framework = arduino
lib_deps  =
    m5stack/M5Unified @ ^0.2.14
    bblanchon/ArduinoJson @ ^7.0.0
build_flags = -DCORE_DEBUG_LEVEL=0
upload_speed = 921600

; ── M5StickC Plus ────────────────────────────────────────────────────────
[env:m5stickc_plus]
platform  = espressif32
board     = m5stick-c
framework = arduino
lib_deps  =
    m5stack/M5Unified @ ^0.2.14
    bblanchon/ArduinoJson @ ^7.0.0
build_flags = -DCORE_DEBUG_LEVEL=0
upload_speed = 921600
